go:
  - 1.1
  - 1.2
  - release
  - tip
  
before_install:
  - go get github.com/nytlabs/streamtools/blocks
  - go get github.com/nytlabs/streamtools/daemon
  - go get github.com/jteeuwen/go-bindata/...
  - go-bindata -pkg=daemon -o daemon/static_bindata.go gui/...
install: make
