go:
  - 1.1
  - 1.2
  - release
  - tip
  
before_install:
  - mkdir -p $GOPATH/src/github.com/nytlabs/streamtools 
  - cp -r * $GOPATH/src/github.com/nytlabs/streamtools 
  - cd $GOPATH/src/github.com/nytlabs/streamtools

install: make
