language: go

go:
  - 1.1
  - 1.2
  - release
  - tip
  
before_install:
  - go get -d github.com/nytlabs/streamtools/blocks
  - go get -d github.com/nytlabs/streamtools/daemon
  - export PATH=/home/travis/gopath/bin:$PATH
  - mkdir -p $GOPATH/src/github.com/nytlabs/streamtools 
  - cp -r * $GOPATH/src/github.com/nytlabs/streamtools 
  - cd $GOPATH/src/github.com/nytlabs/streamtools

install: make
