language: go

go:
  - 1.2
  - release
  
script: "cd st/library && go test"

before_install:
  - export GOPATH=/home/travis/gopath
  - export PATH=$GOPATH/bin:$PATH
  - go get launchpad.net/gocheck
  - go get github.com/mattbaird/elastigo/api
  - go get github.com/mattbaird/elastigo/core

install: make
